language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-cq-ui' ]; then cd .. && eval "mv $currentfolder generator-cq-ui" && cd generator-cq-ui; fi

